version: '3'
services:
  api:
      image: jamshee14/fastapi
      depends_on:
        - postgres
      ports:
        - 80:8000
      environment:
        - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
        - DATABASE_PORT=${DATABASE_PORT}
        - DATABASE_USERNAME=${DATABASE_USERNAME}
        - DATABASE_PASSWORD=${DATABASE_PASSWORD}
        - DATABASE_NAME=${DATABASE_NAME}
        - SECRET_KEY=${SECRET_KEY}
        - ALGORITHM=${ALGORITHM}
        - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
  postgres:
      image: postgres:15
      environment:
        -POSTRES_PASSWORD=${DATABASE_PASSWORD}
        -POSTGRES_USER=${DATABASE_USERNAME}
        -POSTGRES_DB=${DATABASE_NAME}
      volumes:
        - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
