version: '3'
services:
  api:
      build: .
      ports:
        - "8000:8000"
      env_file:
        - ./.env  
#   postgres:
#       image: postgres:15
#       environment:
#         -POSTRES_PASSWORD=%23Jamshee14
#         -POSTGRES_USER=postgres
#         -POSTGRES_DB=fastapi
#       volumes:
#         - postgres_data:/var/lib/postgresql/data
# volumes:
#   postgres_data:
